### ISSUE TITLE
Inconsistent use of `TM`

### ISSUE THREAD

**Issue by Neil-Smithline** [OWASP/www-project-threat-and-safeguard-matrix#1]
[This picture](https://owasp.org/www-project-threat-and-safeguard-matrix/assets/images/CompletedTaSM.png) says that `TASM` is trade marked. That is the only place that I see `TM` on the [project page](https://owasp.org/www-project-threat-and-safeguard-matrix/). I assume that the `TM` is incorrect. If `TASM` is actually trademarked, then OWASP should probably not be using it as it seems contrary to the `O` in `OWASP`.

**Comment by rossayoung** [comment]
fair point this should not be TM.  I have updated the image accordingly
